backend:
  name: github
  repo: Julhk1/slayfashion.lb
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price ($)", name: "price", widget: "number", value_type: "float" }
      - { label: "Category", name: "category", widget: "select", options: ["Tops", "Pants", "Skirts", "Shorts", "Dresses"] }
      - { label: "Available Sizes", name: "sizes", widget: "select", multiple: true, options: ["S", "M", "L", "XL"] }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Product Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
